#!/usr/bin/env node

let converter = require("./converter");
let fs = require('fs');

let usage = function () {
	console.log("converter-cli:");
	console.log("");
	console.log("      node converter-cli.js [import | export] [file to convert]");
	console.log("");
}

let i_or_e = function(order) {
	if (order === "import")
		return converter.JSimport;
	if (order === "export")
		return converter.JSexport;
	return null;
}

let writeGeometry = function(fileName, geometryJSON) {
	let newFileName = fileName.match(/.[^\.]*/g)[0];
	newFileName = newFileName.concat(".json");
	let content = JSON.stringify(geometryJSON.root);
	fs.writeFileSync(newFileName, content, function(err) {
		if(err) {
			return console.log(err);
		}
		console.log("The file was saved!");
	});
}

let main = function (argv) {
	if (argv.length != 4) {
		usage();
		return 0;
	}
	let func = i_or_e(argv[2]);
	if (func === null) {
		console.log(argv[2] + " ::: is not a valide arguments.");
		return 1;
	}
	let geometryJSON = func(argv[3]);
	if (geometryJSON.error.code != 0) {
		console.log(geometryJSON.error.desc);
		return 1;
	}
	writeGeometry(argv[3], geometryJSON);
	return 0;
};

let returnCode = main(process.argv);
process.exit(returnCode)
